-- ============================================================
-- ALAS · Tablero de Facturación Diaria — schema
-- Proyecto Supabase: peusrhpqatobkjwwgmub
-- Ejecutar en el SQL Editor DESPUÉS de drop-old.sql.
-- Patrón snapshot-mirror: el tablero procesa el Excel SAP en el
-- navegador y guarda el snapshot ya calculado (JSON) acá, para que
-- todos vean lo mismo sin volver a subir el archivo.
-- La anon key es pública por diseño; el gate real es el SSO ALAS.
-- NUNCA usar service_role en el cliente.
-- ============================================================

-- ── Snapshot procesado (1 fila por mes; se lee el más reciente) ──
create table if not exists tablero_snapshot (
  id         bigint generated by default as identity primary key,
  anio       int  not null,
  mes        int  not null,               -- 1..12
  snapshot   jsonb not null,              -- objeto completo del tablero (metas, diario, pedidos, etc.)
  updated_by text,
  updated_at timestamptz not null default now(),
  unique (anio, mes)
);
create index if not exists idx_tablero_snapshot_updated on tablero_snapshot(updated_at desc);

-- ── Feriados compartidos (dejan de vivir en localStorage) ──
create table if not exists feriados (
  id          bigint generated by default as identity primary key,
  fecha       date not null unique,
  descripcion text,
  created_at  timestamptz not null default now()
);

-- ── RLS: lectura/escritura anon (el control fino lo hace el SSO en la UI) ──
alter table tablero_snapshot enable row level security;
alter table feriados         enable row level security;

drop policy if exists anon_all on tablero_snapshot;
create policy anon_all on tablero_snapshot for all to anon using (true) with check (true);

drop policy if exists anon_all on feriados;
create policy anon_all on feriados for all to anon using (true) with check (true);

grant usage on schema public to anon, authenticated;
grant all on tablero_snapshot to anon, authenticated;
grant all on feriados         to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;
