-- ============================================================
-- ALAS · Control de Facturas — esquema Supabase (COMPLETO)
-- ------------------------------------------------------------
-- Diseñado para un PROYECTO SUPABASE DEDICADO (autocontenido).
-- Incluye transportadoras y camiones sembrados con los MISMOS IDs
-- que el front ya usa en app.js (transportadoras 1-6, camiones 101-126),
-- así los datos existentes (transportadora_id / camion_id) no se rompen.
--
-- Cómo correrlo:  SQL Editor de Supabase → pegar TODO → Run.
-- Es idempotente: se puede volver a correr sin duplicar.
-- Prefijo fact_ en todas las tablas.
-- ============================================================

-- ============================================================
-- 1) CATÁLOGOS (datos maestros — hoy hardcodeados en el front)
-- ============================================================

-- Transportadoras (flota). IDs 1..6 = SEED_TS de app.js.
create table if not exists fact_transportadoras (
  id     bigint generated by default as identity primary key,
  nombre text not null unique,
  activo boolean not null default true,
  orden  int default 0,
  created_at timestamptz default now()
);

-- Camiones (por transportadora). IDs 101.. = ++tid de app.js.
create table if not exists fact_camiones (
  id                bigint generated by default as identity primary key,
  transportadora_id bigint references fact_transportadoras(id) on delete cascade,
  descripcion       text not null,
  activo            boolean not null default true,
  created_at        timestamptz default now()
);
create index if not exists idx_fact_camiones_ts on fact_camiones(transportadora_id);

-- Repartidores (lista para el desplegable)
create table if not exists fact_repartidores (
  id     bigint generated by default as identity primary key,
  nombre text not null unique,
  activo boolean not null default true,
  created_at timestamptz default now()
);

-- Zonas (Local = Capital / Interior). En repartos se guarda el NOMBRE (texto).
create table if not exists fact_zonas (
  id        bigint generated by default as identity primary key,
  nombre    text not null unique,
  categoria text not null,            -- Local | Interior
  activo    boolean not null default true,
  orden     int default 0,
  created_at timestamptz default now()
);

-- ============================================================
-- 2) OPERACIÓN (planillas, repartos, facturas, auditoría)
-- ============================================================

-- Planilla semanal (por transportadora).
-- estado guardado: 'abierta' | 'auditoria'.
--   El estado MOSTRADO se deriva de la factura vinculada:
--   proceso (sin factura) → conciliada (coincide) → diferencia (no coincide)
--   → auditoria (enviada). Ver planillaStatus() en app.js.
create table if not exists fact_planillas (
  id                    bigint generated by default as identity primary key,
  transportadora_id     bigint,          -- ref lógica a fact_transportadoras (sin FK dura: la flota puede cambiar)
  transportadora_nombre text,
  semana_desde          date,
  semana_hasta          date,
  estado                text not null default 'abierta'
                          check (estado in ('abierta','auditoria')),
  factura_id            bigint,          -- factura asignada (fact_facturas.id)
  created_at            timestamptz default now()
);
create index if not exists idx_fact_planillas_semana on fact_planillas(semana_desde);

-- Reparto (línea de la planilla). Campos = objeto read() del wizard.
-- planilla_id es ref lógica (sin FK dura): el front sincroniza por snapshot y
-- gestiona el borrado en cascada en memoria; sin FK evita choques de orden al sync.
create table if not exists fact_repartos (
  id           bigint generated by default as identity primary key,
  planilla_id  bigint,
  fecha        date,
  tipo         text not null,            -- CAPITAL | INTERIOR | SERVICIOS ADICIONALES
  repartidor   text,
  zona         text,
  camion_id    bigint,                   -- ref lógica a fact_camiones.id
  camion_desc  text,
  km           numeric default 0,
  precio       numeric default 0,
  observacion  text,
  orden        int default 0,
  created_at   timestamptz default now()
);
create index if not exists idx_fact_repartos_planilla on fact_repartos(planilla_id);

-- Factura (llega y se asigna a una planilla).
create table if not exists fact_facturas (
  id                    bigint generated by default as identity primary key,
  nro                   text,
  fecha                 date,
  transportadora_id     bigint,
  transportadora_nombre text,
  monto                 numeric default 0,
  planilla_id           bigint,          -- ref lógica (sin FK dura, ver nota en fact_repartos)
  created_at            timestamptz default now()
);
create index if not exists idx_fact_facturas_planilla on fact_facturas(planilla_id);

-- Auditoría (bitácora de acciones = DB.audit de app.js).
create table if not exists fact_audit (
  id          bigint generated by default as identity primary key,
  ts          timestamptz not null default now(),   -- app guarda ISO string
  accion      text not null,        -- crear_planilla | agregar_repartos | enviar_auditoria | reabrir | borrar_planilla | registrar_factura ...
  usuario     text,
  detalle     text,
  chips       text[] default '{}',  -- etiquetas cortas (montos, nº repartos, semana)
  planilla_id bigint,               -- ref lógica (sin FK: la auditoría sobrevive al borrado)
  created_at  timestamptz default now()
);
create index if not exists idx_fact_audit_ts on fact_audit(ts desc);
create index if not exists idx_fact_audit_planilla on fact_audit(planilla_id);

-- ============================================================
-- 3) RLS + GRANTS (patrón del ecosistema: anon con RLS abierto)
--    La seguridad real vive en el login SSO del launcher.
-- ============================================================
alter table fact_transportadoras enable row level security;
alter table fact_camiones        enable row level security;
alter table fact_repartidores    enable row level security;
alter table fact_zonas           enable row level security;
alter table fact_planillas       enable row level security;
alter table fact_repartos        enable row level security;
alter table fact_facturas        enable row level security;
alter table fact_audit           enable row level security;

do $$ declare t text; begin
  foreach t in array array[
    'fact_transportadoras','fact_camiones','fact_repartidores','fact_zonas',
    'fact_planillas','fact_repartos','fact_facturas','fact_audit'
  ] loop
    execute format('drop policy if exists anon_all on %I;', t);
    execute format('create policy anon_all on %I for all to anon using (true) with check (true);', t);
  end loop; end $$;

grant usage on schema public to anon, authenticated;
grant all on all tables    in schema public to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;
alter default privileges in schema public grant all on tables    to anon, authenticated;
alter default privileges in schema public grant all on sequences to anon, authenticated;

-- ============================================================
-- 4) SEED — catálogos (IDs idénticos a app.js)
-- ============================================================

-- Transportadoras (SEED_TS: id 1..6)
insert into fact_transportadoras (id, nombre, orden) values
  (1,'ALAS',1),
  (2,'SL',2),
  (3,'BG',3),
  (4,'CR',4),
  (5,'TRANSMAQ ORTEGA',5),
  (6,'ANTONIO BAEZ',6)
on conflict (id) do nothing;

-- Camiones (++tid arranca en 101, en el orden exacto de SEED_TS)
insert into fact_camiones (id, transportadora_id, descripcion) values
  -- ALAS (1) → 101..106
  (101,1,'ALAS HYUNDAI'),
  (102,1,'ALAS Mercedes Benz 1315 BBH909B'),
  (103,1,'ALAS Mercedes Benz 709 AADX129'),
  (104,1,'ALAS Mercedes Benz 711 AOZ758'),
  (105,1,'ALAS FUSO AADP885'),
  (106,1,'ALAS Furgon-Foton'),
  -- SL (2) → 107..110
  (107,2,'SL MB814 AAVG562 (SIMPLE)'),
  (108,2,'SL MB 914 HDJ075 CELESTE'),
  (109,2,'SL MB814 BXC396 BLANCO (RAMPA)'),
  (110,2,'SL SCANIA DOBLE EJE'),
  -- BG (3) → 111..119
  (111,3,'BG MOVIL 08 HFH-440'),
  (112,3,'BG MOVIL 09 AYE-466'),
  (113,3,'BG MOVIL 10 AAFI-477'),
  (114,3,'BG MOVIL 11 BOZ-074'),
  (115,3,'BG MOVIL 13 AAFL-766'),
  (116,3,'BG MOVIL 14 XBL-816'),
  (117,3,'BG MOVIL 21 BRX-972'),
  (118,3,'BG MOVIL 25 AASI-849'),
  (119,3,'BG MOVIL 26 AASM-682'),
  -- CR (4) → 120..122
  (120,4,'CR Scania 05 AAN498'),
  (121,4,'CR Scania 06 HFR039'),
  (122,4,'CR Scania 07 BRF403'),
  -- TRANSMAQ ORTEGA (5) → 123..124
  (123,5,'TRANSMAQ VOLKSWAGEN AHN624'),
  (124,5,'TRANSMAQ-SEMI'),
  -- ANTONIO BAEZ (6) → 125..126
  (125,6,'Mercedes Benz Atego 815'),
  (126,6,'ANTONIO BAEZ Scania HEU859 VERDE')
on conflict (id) do nothing;

-- Repartidores (lista completa)
insert into fact_repartidores (nombre) values
  ('TERCERIZADO'),
  ('Adilson Galeano'),('Alberto Britez'),('Alejandro Alvarenga'),('Alexis Gimenez'),
  ('Amilcar Garcia'),('Angel Zorrilla'),('Axel Mendieta'),('Candido Diaz'),
  ('Carlos Barreto'),('Carlos Galeano'),('Carlos Penayo'),('Celso Gamarra'),
  ('Cristhian Santa cruz'),('Cristhofer Castillo'),('Cristian Santacruz'),('Enrrique Arza'),
  ('Francisco del Puerto'),('Francisco Rivas'),('Guillermo Mencia'),('Gustavo Benitez'),
  ('Joel Benitez'),('Jorge Estigarribia'),('Juan Balmori'),('Julio Velilla'),
  ('Lisandro Lopez'),('Lucas Maqueda'),('Maicol Benitez'),('Manuel Martinez'),
  ('Marcos Aveiro'),('Nahuel Castillo'),('Nestor Miranda'),('Pedro Riveros'),
  ('Reinaldo Ferreira'),('Sebastian Baez'),('Tomas Quiñonez'),('Tomas Bernal'),
  ('Eugenio Villar'),('Angel Denis'),('JOSE SEGOVIA'),('JESUS ESCOBAR'),
  ('ENZO RUFINELI'),('SERGIO AGUILERA'),('Denis GONZALEZ')
on conflict (nombre) do nothing;

-- Zonas (Local = Capital / Interior) — orden = ZONAS de app.js
insert into fact_zonas (nombre,categoria,orden) values
  ('PR1 Asunción','Local',1),('PR2 Luque','Local',2),('PR3 San Lorenzo','Local',3),
  ('PR4 Capiatá','Local',4),('PR5 Itauguá','Local',5),('PR5 Ypacaraí','Local',6),
  ('PR6 Augusto Saldívar','Local',7),('PR6 Itá','Local',8),('PR7 Areguá','Local',9),
  ('PR8 Limpio','Local',10),('PR8 Loma Pytá','Local',11),('PR8 M.R.A.','Local',12),
  ('PR9 San Antonio','Local',13),('PR9 Ypané','Local',14),('PR9 Ñemby','Local',15),
  ('PR10 Nueva Italia','Local',16),('PR10 Guarambaré','Local',17),('PR10 Villeta','Local',18),
  ('PR11 Fernando de la Mora','Local',19),('PR11 Villa Elisa','Local',20),('PR12 Lambaré','Local',21),
  ('PR13 Cordillera','Local',22),('PR14 Nanawa','Local',23),('PR14 Villa Hayes','Local',24),
  ('PR15 Paraguarí','Local',25),
  ('NORTE','Interior',101),('ESTE','Interior',102),('SUR','Interior',103),
  ('CAAGUAZU','Interior',104),('CAAZAPA','Interior',105),('VILLARRICA','Interior',106),
  ('CHACO','Interior',107)
on conflict (nombre) do nothing;

-- ============================================================
-- 5) Reajustar las secuencias identity tras sembrar IDs explícitos
--    (para que los próximos INSERT sin id no choquen con los seeds)
-- ============================================================
select setval(pg_get_serial_sequence('fact_transportadoras','id'),
              greatest((select max(id) from fact_transportadoras), 1));
select setval(pg_get_serial_sequence('fact_camiones','id'),
              greatest((select max(id) from fact_camiones), 1));
select setval(pg_get_serial_sequence('fact_repartidores','id'),
              greatest((select max(id) from fact_repartidores), 1));
select setval(pg_get_serial_sequence('fact_zonas','id'),
              greatest((select max(id) from fact_zonas), 1));

-- ============================================================
-- FIN. Tablas: fact_transportadoras, fact_camiones, fact_repartidores,
-- fact_zonas, fact_planillas, fact_repartos, fact_facturas, fact_audit.
-- ============================================================
